#!  /usr/bin/env bash

#   Autostart
$HOME./config/bspwm/autostart.sh

#   Set environment
bspc monitor -d I II III IV V 
#   bspc monitor HDMI-0 VI VII VIII IX X

bspc config border_width    2
bspc config window_gap      12
bspc config split_ration    0.52

bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config bottom_padding      46

bspc rule -a qutebrowser desktop='^2'
bspc rule -a chromium desktop='^2'
#bspc rule -a Gimp desktop='^4' state=floating follow=on
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

