#!  /usr/bin/env bash

#   Autostart
sxhkd   &
#   Set environment


bspc monitor -d 1 2 3 4

bspc config border_width    2
bspc config window_gap      12

bspc config split_ration    0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc rule -a qutebrowser desktop='^2'
bspc rule -a chromium desktop='^2'
bspc rule -a gimp desktop='^4' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

